kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-deployments-microservice-vault
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pods-microservice-vault
  template:
    metadata:
      name: {{ .Chart.Name }}-pods-microservice-vault
      labels:
        app: {{ .Chart.Name }}-pods-microservice-vault
    spec:
      containers:
        - name: {{ .Chart.Name }}-pods-microservice-vault
          image: {{ .Values.microservices.vault }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets-db-urls
                  key: database-vault-url
