apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-services-users
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-pods-microservice-users
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
