apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-services-application-roadblock-api
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-pods-application-roadblock-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
